name: "Setup and install"
description: "Setup and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "1.3.5"

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - shell: bash
      run: bun install --frozen-lockfile