name: 'Saltman'
description: 'Analyzes PR content and posts results as a comment'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  openai-api-key:
    description: 'OpenAI API key for LLM code review'
    required: true
  post-comment:
    description: 'Whether to post the analysis as a comment on the PR (true/false). Defaults to false if not specified.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
    - name: Build
      shell: bash
      run: bun run build
    - name: Run action
      shell: bash
      run: bun dist/main.js
      env:
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_OPENAI-API-KEY: ${{ inputs.openai-api-key }}
        INPUT_POST-COMMENT: ${{ inputs.post-comment }}

